### ISSUE TITLE
Doubt how to launch the library

### ISSUE THREAD

**Issue by juannavalonribas** [bamlab/android-performance-profiler#63]
Hello 👋🏻 ,

First of all congratulations on your work and your contribution to the community. 

I have a doubt in order to launch the library

We use yarn and our command to launch the tests is determined by different parameters example:

`npx @perf-profiler/e2e measure --bundleId xxx --testCommand "yarn e2e:android:local:fr" --duration 100000 --resultsFilePath results.json`

The test runs but the process continues and does nothing.

Any suggestion?

Thanks!

**Comment by Almouro** [comment]
Hi @juannavalonribas, thanks for the congratulations! 😊

A few questions on my side:

- what e2e framework are you using? what does `yarn e2e:android:local:fr` run?
- can you share a copy of the logs you see in the terminal when running `npx @perf-profiler/e2e measure ...`?
- what OS are you running on?

**Comment by juannavalonribas** [comment]
Hello @Almouro,

I am using appium@next (appium 2) with webdriverIO all in javascript. The command I am launching is `"e2e:android:local:fr": "TEST_COUNTRY='FR' TEST_ENV=E2E yarn e2e:android:local --suite login",`
Where e2e:android:local = ` "e2e:android:local": "TEST_ENV=E2E wdio ./e2e/config/wdio.android.local.conf.js",`

 Logs:
`[16:59:28] ℹ️  Installing C++ profiler for arm64-v8a architecture
[16:59:28] ✅  C++ Profiler installed in /data/local/tmp/BAMPerfProfiler
[16:59:29] ℹ️  Running iteration 1/10
`
And then the test is executed properly and ends showing:
`Spec Files:      1 passed, 1 total (100% completed) in 00:00:33 
✨  Done in 36.05s.
`
But the "process" is still running with no more iterations

Running the command locally in a macbook m1 macOs Ventura 13.0.1 through webstorm terminal

**Comment by juannavalonribas** [comment]
ohh It was a missunderstanding.. true is working properly. But I have another question currently the json results.json report appears empty regarding the current json https://gist.github.com/juannavalonribas/35d53300e408d9d482876348443ab314

Any idea?

**Comment by Almouro** [comment]
Oh that's not normal indeed

I've tried quickly with a small `wdio` example and cannot reproduce this.  
Would you be able to reproduce this with a very simple test on your app? Something like:

```js
describe("Very simple test", () => {
  it("finds the text", async () => {
    const text = "random text";
    const element = await $(
      `//*[contains(@text,'${text}')] |`
    );
    await element.waitForDisplayed({ timeout: 30000 });
    // Just wait for 5s to make sure we have performance measures before the app stops
    await new Promise((resolve) => setTimeout(resolve, 5000));
  });
});
```

Also is the app stopping and starting during the e2e test? We expect the test to start the app and never stop it (except at the end potentially)

**Comment by juannavalonribas** [comment]
It works with this simple example
```
describe(`Performance in ${country.countryCode}`, () => {
  beforeEach(async () => {
    await checkAppStatus();
  });
  it('Just Click in login button', async () => {
    await HomeScreen.goToLogin();
    await new Promise(resolve => setTimeout(resolve, 5000));
  });
});
```

appium capabilities:
```
        'appium:noReset': false,
        'appium:fullReset': false,
```

I am going to investigate what might be happening. The previous case I had tried it with a suite that only contains 1 test.

**Comment by juannavalonribas** [comment]
Hello!

I have tried using my real device connected in local env and it works perfect. Now im facing the challenge launching the test against browserstack.

I close this "doubt" cause has been resolved.
Thank

**Comment by Almouro** [comment]
@juannavalonribas Up to my knowledge, Browserstack sadly doesn't allow adb access so this lib won't work (https://github.com/bamlab/android-performance-profiler#running-in-ci for more details)
